spring:
  application:
    name: slave

server:
  port: 2613

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    #        defaultZone: http://localhost:8761/eureka/
    #        defaultZone: http://localhost:1234/eureka/
    fetch-registry: true
    register-with-eureka: true